name: ponomar_web
description: "Ponomar Telegram app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  telegram_web_app: ^0.1.5
  easy_localization: ^3.0.7
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  jiffy: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/ru-RU/

